-- AlterTable
ALTER TABLE "payments" ADD COLUMN     "coins_redeemed" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;
